#pragma once


#include <filesystem>
#include <vector>

#include "../Math/Matrix4x4.h"
#include "../Math/Vector2.h"

#include "../sdk/Camera.h"
#include "../sdk/GameInstance.h"
#include "../sdk/DefaultMovementController.h"
#include "../sdk/App.h"
#include "../sdk/Entity.h"

inline const char* get_packet_name(int id)
{
    switch (id)
    {
    case 0: return "Connect";
    case 1: return "Disconnect";
    case 2: return "Ping";
    case 3: return "Pong";
    case 10: return "Status";
    case 11: return "AuthGrant";
    case 12: return "AuthToken";
    case 13: return "ServerAuthToken";
    case 14: return "ConnectAccept";
    case 15: return "PasswordResponse";
    case 16: return "PasswordAccepted";
    case 17: return "PasswordRejected";
    case 18: return "ClientReferral";
    case 20: return "WorldSettings";
    case 21: return "WorldLoadProgress";
    case 22: return "WorldLoadFinished";
    case 23: return "RequestAssets";
    case 24: return "AssetInitialize";
    case 25: return "AssetPart";
    case 26: return "AssetFinalize";
    case 27: return "RemoveAssets";
    case 28: return "RequestCommonAssetsRebuild";
    case 29: return "SetUpdateRate";
    case 30: return "SetTimeDilation";
    case 31: return "UpdateFeatures";
    case 32: return "ViewRadius";
    case 33: return "PlayerOptions";
    case 34: return "ServerTags";
    case 40: return "UpdateBlockTypes";
    case 41: return "UpdateBlockHitboxes";
    case 42: return "UpdateBlockSoundSets";
    case 43: return "UpdateItemSoundSets";
    case 44: return "UpdateBlockParticleSets";
    case 45: return "UpdateBlockBreakingDecals";
    case 46: return "UpdateBlockSets";
    case 47: return "UpdateWeathers";
    case 48: return "UpdateTrails";
    case 49: return "UpdateParticleSystems";
    case 50: return "UpdateParticleSpawners";
    case 51: return "UpdateEntityEffects";
    case 52: return "UpdateItemPlayerAnimations";
    case 53: return "UpdateModelvfxs";
    case 54: return "UpdateItems";
    case 55: return "UpdateItemQualities";
    case 56: return "UpdateItemCategories";
    case 57: return "UpdateItemReticles";
    case 58: return "UpdateFieldcraftCategories";
    case 59: return "UpdateResourceTypes";
    case 60: return "UpdateRecipes";
    case 61: return "UpdateEnvironments";
    case 62: return "UpdateAmbienceFX";
    case 63: return "UpdateFluidFX";
    case 64: return "UpdateTranslations";
    case 65: return "UpdateSoundEvents";
    case 66: return "UpdateInteractions";
    case 67: return "UpdateRootInteractions";
    case 68: return "UpdateUnarmedInteractions";
    case 69: return "TrackOrUpdateObjective";
    case 70: return "UntrackObjective";
    case 71: return "UpdateObjectiveTask";
    case 72: return "UpdateEntityStatTypes";
    case 73: return "UpdateEntityUIComponents";
    case 74: return "UpdateHitboxCollisionConfig";
    case 75: return "UpdateRepulsionConfig";
    case 76: return "UpdateViewBobbing";
    case 77: return "UpdateCameraShake";
    case 78: return "UpdateBlockGroups";
    case 79: return "UpdateSoundSets";
    case 80: return "UpdateAudioCategories";
    case 81: return "UpdateReverbEffects";
    case 82: return "UpdateEqualizerEffects";
    case 83: return "UpdateFluids";
    case 84: return "UpdateTagPatterns";
    case 85: return "UpdateProjectileConfigs";
    case 100: return "SetClientId";
    case 101: return "SetGameMode";
    case 102: return "SetMovementStates";
    case 103: return "SetBlockPlacementOverride";
    case 104: return "JoinWorld";
    case 105: return "ClientReady";
    case 106: return "LoadHotbar";
    case 107: return "SaveHotbar";
    case 108: return "ClientMovement";
    case 109: return "ClientTeleport";
    case 110: return "UpdateMovementSettings";
    case 111: return "MouseInteraction";
    case 112: return "DamageInfo";
    case 113: return "ReticleEvent";
    case 114: return "DisplayDebug";
    case 115: return "ClearDebugShapes";
    case 116: return "SyncPlayerPreferences";
    case 117: return "ClientPlaceBlock";
    case 118: return "UpdateMemoriesFeatureStatus";
    case 119: return "RemoveMapMarker";
    case 131: return "SetChunk";
    case 132: return "SetChunkHeightmap";
    case 133: return "SetChunkTintmap";
    case 134: return "SetChunkEnvironments";
    case 135: return "UnloadChunk";
    case 136: return "SetFluids";
    case 140: return "ServerSetBlock";
    case 141: return "ServerSetBlocks";
    case 142: return "ServerSetFluid";
    case 143: return "ServerSetFluids";
    case 144: return "UpdateBlockDamage";
    case 145: return "UpdateTimeSettings";
    case 146: return "UpdateTime";
    case 147: return "UpdateEditorTimeOverride";
    case 148: return "ClearEditorTimeOverride";
    case 149: return "UpdateWeather";
    case 150: return "UpdateEditorWeatherOverride";
    case 151: return "UpdateEnvironmentMusic";
    case 152: return "SpawnParticleSystem";
    case 153: return "SpawnBlockParticleSystem";
    case 154: return "PlaySoundEvent2D";
    case 155: return "PlaySoundEvent3D";
    case 156: return "PlaySoundEventEntity";
    case 157: return "UpdateSleepState";
    case 158: return "SetPaused";
    case 159: return "ServerSetPaused";
    case 160: return "SetEntitySeed";
    case 161: return "EntityUpdates";
    case 162: return "PlayAnimation";
    case 163: return "ChangeVelocity";
    case 164: return "ApplyKnockback";
    case 165: return "SpawnModelParticles";
    case 166: return "MountMovement";
    case 170: return "UpdatePlayerInventory";
    case 171: return "SetCreativeItem";
    case 172: return "DropCreativeItem";
    case 173: return "SmartGiveCreativeItem";
    case 174: return "DropItemStack";
    case 175: return "MoveItemStack";
    case 176: return "SmartMoveItemStack";
    case 177: return "SetActiveSlot";
    case 178: return "SwitchHotbarBlockSet";
    case 179: return "InventoryAction";
    case 200: return "OpenWindow";
    case 201: return "UpdateWindow";
    case 202: return "CloseWindow";
    case 203: return "SendWindowAction";
    case 204: return "ClientOpenWindow";
    case 210: return "ServerMessage";
    case 211: return "ChatMessage";
    case 212: return "Notification";
    case 213: return "KillFeedMessage";
    case 214: return "ShowEventTitle";
    case 215: return "HideEventTitle";
    case 216: return "SetPage";
    case 217: return "CustomHud";
    case 218: return "CustomPage";
    case 219: return "CustomPageEvent";
    case 222: return "EditorBlocksChange";
    case 223: return "ServerInfo";
    case 224: return "AddToServerPlayerList";
    case 225: return "RemoveFromServerPlayerList";
    case 226: return "UpdateServerPlayerList";
    case 227: return "UpdateServerPlayerListPing";
    case 228: return "UpdateKnownRecipes";
    case 229: return "UpdatePortal";
    case 230: return "UpdateVisibleHudComponents";
    case 231: return "ResetUserInterfaceState";
    case 232: return "UpdateLanguage";
    case 233: return "WorldSavingStatus";
    case 234: return "OpenChatWithCommand";
    case 240: return "UpdateWorldMapSettings";
    case 241: return "UpdateWorldMap";
    case 242: return "ClearWorldMap";
    case 243: return "UpdateWorldMapVisible";
    case 244: return "TeleportToWorldMapMarker";
    case 245: return "TeleportToWorldMapPosition";
    case 250: return "RequestServerAccess";
    case 251: return "UpdateServerAccess";
    case 252: return "SetServerAccess";
    case 260: return "RequestMachinimaActorModel";
    case 261: return "SetMachinimaActorModel";
    case 262: return "UpdateMachinimaScene";
    case 280: return "SetServerCamera";
    case 281: return "CameraShakeEffect";
    case 282: return "RequestFlyCameraMode";
    case 283: return "SetFlyCameraMode";
    case 290: return "SyncInteractionChains";
    case 291: return "CancelInteractionChain";
    case 292: return "PlayInteractionFor";
    case 293: return "MountNPC";
    case 294: return "DismountNPC";
    case 300: return "FailureReply";
    case 301: return "SuccessReply";
    case 302: return "AssetEditorInitialize";
    case 303: return "AssetEditorAuthorization";
    case 304: return "AssetEditorCapabilities";
    case 305: return "AssetEditorSetupSchemas";
    case 306: return "AssetEditorSetupAssetTypes";
    case 307: return "AssetEditorCreateDirectory";
    case 308: return "AssetEditorDeleteDirectory";
    case 309: return "AssetEditorRenameDirectory";
    case 310: return "AssetEditorFetchAsset";
    case 311: return "AssetEditorFetchJsonAssetWithParents";
    case 312: return "AssetEditorFetchAssetReply";
    case 313: return "AssetEditorFetchJsonAssetWithParentsReply";
    case 314: return "AssetEditorAssetPackSetup";
    case 315: return "AssetEditorUpdateAssetPack";
    case 316: return "AssetEditorCreateAssetPack";
    case 317: return "AssetEditorDeleteAssetPack";
    case 318: return "AssetEditorEnableAssetPack";
    case 319: return "AssetEditorAssetListSetup";
    case 320: return "AssetEditorAssetListUpdate";
    case 321: return "AssetEditorRequestChildrenList";
    case 322: return "AssetEditorRequestChildrenListReply";
    case 323: return "AssetEditorUpdateJsonAsset";
    case 324: return "AssetEditorUpdateAsset";
    case 325: return "AssetEditorJsonAssetUpdated";
    case 326: return "AssetEditorAssetUpdated";
    case 327: return "AssetEditorCreateAsset";
    case 328: return "AssetEditorRenameAsset";
    case 329: return "AssetEditorDeleteAsset";
    case 330: return "AssetEditorDiscardChanges";
    case 331: return "AssetEditorFetchAutoCompleteData";
    case 332: return "AssetEditorFetchAutoCompleteDataReply";
    case 333: return "AssetEditorRequestDataset";
    case 334: return "AssetEditorRequestDatasetReply";
    case 335: return "AssetEditorActivateButton";
    case 336: return "AssetEditorSelectAsset";
    case 337: return "AssetEditorPopupNotification";
    case 338: return "AssetEditorFetchLastModifiedAssets";
    case 339: return "AssetEditorLastModifiedAssets";
    case 340: return "AssetEditorModifiedAssetsCount";
    case 341: return "AssetEditorSubscribeModifiedAssetsChanges";
    case 342: return "AssetEditorExportAssets";
    case 343: return "AssetEditorExportAssetInitialize";
    case 344: return "AssetEditorExportAssetPart";
    case 345: return "AssetEditorExportAssetFinalize";
    case 346: return "AssetEditorExportDeleteAssets";
    case 347: return "AssetEditorExportComplete";
    case 348: return "AssetEditorRebuildCaches";
    case 349: return "AssetEditorUndoChanges";
    case 350: return "AssetEditorRedoChanges";
    case 351: return "AssetEditorUndoRedoReply";
    case 352: return "AssetEditorSetGameTime";
    case 353: return "AssetEditorUpdateSecond[removed]ameDay";
    case 354: return "AssetEditorUpdateWeatherPreviewLock";
    case 355: return "AssetEditorUpdateModelPreview";
    case 360: return "UpdateSunSettings";
    case 361: return "UpdatePostFxSettings";
    case 400: return "BuilderToolArgUpdate";
    case 401: return "BuilderToolEntityAction";
    case 402: return "BuilderToolSetEntityTransform";
    case 403: return "BuilderToolExtrudeAction";
    case 404: return "BuilderToolStackArea";
    case 405: return "BuilderToolSelectionTransform";
    case 406: return "BuilderToolRotateClipboard";
    case 407: return "BuilderToolPasteClipboard";
    case 408: return "BuilderToolSetTransformationModeState";
    case 409: return "BuilderToolSelectionUpdate";
    case 410: return "BuilderToolSelectionToolAskForClipboard";
    case 411: return "BuilderToolSelectionToolReplyWithClipboard";
    case 412: return "BuilderToolGeneralAction";
    case 413: return "BuilderToolOnUseInteraction";
    case 414: return "BuilderToolLineAction";
    case 415: return "BuilderToolShowAnchor";
    case 416: return "BuilderToolHideAnchors";
    case 417: return "PrefabUnselectPrefab";
    case 418: return "BuilderToolsSetSoundSet";
    case 419: return "BuilderToolLaserPointer";
    case 420: return "BuilderToolSetEntityScale";
    case 421: return "BuilderToolSetEntityPickupEnabled";
    case 422: return "BuilderToolSetEntityLight";
    case 423: return "BuilderToolSetNPCDebug";
    default: return "Unknown_Packet";
    }
}

struct SimpleTime
{
    int hour;
    int minute;
    int second;
    int millisecond;
};

namespace Util {

    inline App* app;
    Entity* getLocalPlayer();
    GameInstance* getGameInstance();
    Camera* getCamera();
    std::vector<Entity*> getEntities();
    inline Matrix4x4 viewProjMat;
    inline DefaultMovementController* dmc;

    inline float windowWidth = 0;
    inline float windowHeight = 0;
    inline float cursorPosX = 0;
    inline float cursorPosY = 0;
   
    bool WorldToScreen(Vector3 pos, Vector2& out);
    void ResetGlobals();
    Matrix4x4 getViewProjMat();
    std::filesystem::path GetDirectory();
    SimpleTime HoursToTime(float hours);
    __int64 BuildTicksFromHours(float hours);
}